# Generated by Django 5.0.4 on 2024-04-06 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ventas',
            new_name='Venta',
        ),
    ]
